### ISSUE TITLE
/app/bin/server failing the read command

### ISSUE THREAD

**Issue by smashedtoatoms** [davydog187/website#19]
I was working off of [this](https://github.com/davydog187/website/blob/main/priv/blogs/2022/08-03-observing-elixir-with-lightstep.md) and in the `rel/overlays/bin/server` script, I ran into an issue with the `read` command.  

Specifically, the error was:
```
2022-09-07T22:18:27Z   [info]Preparing to run: `/app/bin/server` as nobody
2022-09-07T22:18:27Z   [info]2022/09/07 22:18:27 listening on [fdaa:0:869c:a7b:a15f:9c9:7b6b:2]:22 (DNS: [fdaa::3]:53)
2022-09-07T22:18:27Z   [info]/app/bin/server: 6: read: Illegal option -d
2022-09-07T22:18:28Z   [info]Starting clean up.
```

It is very likely that this is a problem specific to my setup, but I figured I would ask if you had any ideas.

**Comment by smashedtoatoms** [comment]
Nevermind, I sorted it out.  The problem is that the `#!/bin/sh` shell in my docker container doesn't support `-d`.  I switched the script to a bash shebang, and it deployed fine.  For reference, if anyone else runs into this, do something like this in your `rel/overlays/bin/server` file (the magic is in the first line):

```
#!/bin/bash
cd -P -- "$(dirname -- "$0")"

# This adds annotations so all of my otel spans have information about the
# environment in which they execute.
read -r -d '' attributes <<EOM
service.name=${FLY_APP_NAME},
service.instance.id=${FLY_ALLOC_ID},
cloud.provider=fly_io,
cloud.region.id=${FLY_REGION}
EOM

readonly OTEL_RESOURCE_ATTRIBUTES=$(echo $attributes | sed 's/[[:space:]]//g')

OTEL_RESOURCE_ATTRIBUTES=${OTEL_RESOURCE_ATTRIBUTES} \
  PHX_SERVER=true \
  exec ./your-app start
``` 

__Great doc, by the way!__

**Comment by davydog187** [comment]
Glad you figured it out @smashedtoatoms! Care to send a PR to help the next person?

**Comment by smashedtoatoms** [comment]
Yep!  I will once I get past the next thing.  I jumped out of that error into a different one.

**Comment by smashedtoatoms** [comment]
Well, I spoke too soon.  It all works locally, but it does nothing in fly.  No errors, nothing.  You don't happen to have an example of your docker file or release settings that you can share do you?  I have config in my runtime.exs with hard-coded values and it still does absolutely nothing.

**Comment by smashedtoatoms** [comment]
I have gone deep down a hole on this one.  If you get a chance to take a look at this, I started with your config and none of the data is making it out of fly to my honeycomb.  I stripped down the config and opentelemetry isn't even writing to stdout in fly... but works locally.  It is very strange.  If you had any experience like this I'd love to hear about it.  If not, I totally get it.  Thanks so much either way.

- https://community.fly.io/t/getting-honeycomb-opentelemetry-working-with-distributed-elixir-phoenix-postgres/7048
- https://github.com/open-telemetry/opentelemetry-erlang/issues/458

**Comment by davydog187** [comment]
Thanks for the update @smashedtoatoms, I'm really sorry that you're experiencing so much trouble! Based on what you've posted I don't see anything obviously wrong :(

These are my current versions if that's helpful

```
$ mix deps | grep opentelemetry
* opentelemetry 1.0.5 (Hex package) (rebar3)
  locked at 1.0.5 (opentelemetry) 3b17f893
* opentelemetry_api 1.0.3 (Hex package) (mix)
  locked at 1.0.3 (opentelemetry_api) 4293e06b
* opentelemetry_ecto 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (opentelemetry_ecto) 39cc60db
* opentelemetry_liveview 1.0.0-rc.4 (Hex package) (mix)
  locked at 1.0.0-rc.4 (opentelemetry_liveview) e06ab69d
* opentelemetry_oban 0.2.0-rc.5 (Hex package) (mix)
  locked at 0.2.0-rc.5 (opentelemetry_oban) 34b91e44
* opentelemetry_phoenix 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (opentelemetry_phoenix) 9cb30018
* opentelemetry_process_propagator 0.1.1 (Hex package) (mix)
  locked at 0.1.1 (opentelemetry_process_propagator) 0572f260
* opentelemetry_telemetry 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (opentelemetry_telemetry) 3401d13a
```

**Comment by smashedtoatoms** [comment]
Oh man, it got wild.  If you get a chance, go read [this thread](https://community.fly.io/t/getting-honeycomb-opentelemetry-working-with-distributed-elixir-phoenix-postgres/7048).  The gist of it is that Fly.io started injecting `traceparent` and  `tracestate` into requests.  The elixir/erlang opentelemetry libraries do their job and respect those headers, which set the sample rate to Fly's, which is %0.02, effectively turning them off for my site receiving a half-dozen requests a day.  That's why it worked locally, and not in my Fly containers.  They have updated the headers for internal use, and everything works correctly now.  I will update the doc with the scripting changes I encountered.  It seems less useful to crud up the otherwise beautiful doc with my weird opentelemetry birthing experience.

**Comment by davydog187** [comment]
oh my god! Definitely going to dig into the thread, sounds like a wild goose chase. I'm glad you got it sorted
